/* AUTOGENERATED BY tool DO NOT MODIFY */
#define VARS_NUM 0
#pragma data_seg(".vars_data")
#pragma data_seg(".vars.metadata")
static const unsigned int vars_metadata[] = {
	};
#pragma data_seg(".vars.times")
static const unsigned int vars_timedeltas[] = {
	};
#pragma data_seg(".vars.values")
static const float vars_values[] = {
	};
